config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :goals
  resources :users
  root to: 'goals#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  get '/about' => 'visitors#about'

  namespace :api do
    namespace :v1 do
      resources :goals, only: [:index, :show]
    end
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  extend Importable

  has_many :reviews
  has_many :players, through: :reviews, class_name: 'User', foreign_key: :player_id

  def labels_hash_array
    return 'None' unless github_import && github_import['labels']
    github_import['labels']
  end

  def labels
    labels_hash_array.map{ |label| label['name'] }
  end

  def draft?
    labels.include? "draft"
  end

  def description
    github_import['body']
  end

  def id_title
    "#{id} — #{title}"
  end

  def issue_path
    "http://github.com/GuildCrafts/web-development-js/issues/#{id}"
  end

  def title
    return 'None' unless github_import && github_import['title']
    github_import['title']
  end

  def created_by
    return 'None' unless github_import && github_import['user']
    github_import['user']['login']
  end

  def created
    return 'None' unless github_import && github_import['created_at']
    DateTime.strptime(github_import['created_at'])
  end
  
  def self.create_from_github(goal_id)
    goal_json = github("https://api.github.com/repos/GuildCrafts/web-development-js/issues/#{goal_id.to_s}")

    existing = Goal.find_or_initialize_by(id: goal_id)
    if existing.persisted?
      puts "Updating goal ##{goal_id}."
      existing.update(github_import: goal_json)
    else
      puts "Creating goal ##{goal_id}."
      create! do |goal|
        goal.id = goal_id
        goal.github_import = goal_json
      end
    end
  end

  def self.importable_ids
    goal_json = github('https://api.github.com/repos/GuildCrafts/web-development-js/issues')
    goal_json.map{ |g| g["number"] }
  end

  def self.sync_all
    importable_ids.map{ |id| create_from_github(id) }
  end

  def self.last_update
    all.map(&:updated_at).max
  end
end

app/controllers/api/v1/goals_controller.rb
class Api::V1::GoalsController < Api::V1::BaseController
  def index
    goals = Goal.order(:id)

    render(json: goals)
  end

  def show
    goal = Goal.find(params[:id])

    render(json: goal)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  def index
    @goals = Goal.order(:id)
  end

  def show
  end

  def new
    @goal = Goal.new
    @importable_ids = Goal.importable_ids.sort
  end

  def edit
  end

  def create_with_github
    raise
  end

  def create
    if goal_id = params['goal']['id']
      @goal = Goal.create_from_github(goal_id)
    else
      @goal = Goal.new(goal_params)
    end

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to goals_path, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_goal
      @goal = Goal.find(params[:id])
    end

    def goal_params
      params.require(:goal).permit(:github_import, :tried, :up, :down)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.haml
= simple_form_for(@goal) do |f|
  = f.error_notification

  .form-inputs
    = f.input :id, collection: @importable_ids, label: 'web-development-js issue id'

  .form-actions
    = f.button :submit

app/views/goals/_labels.html.haml
- goal.labels_hash_array.each do |labels_hash|
  .tag{'style' => "background-color: ##{labels_hash['color']};"}= labels_hash['name']

app/views/goals/edit.html.haml
%h1 Edit Goal

%h4= @goal.title

= simple_form_for(@goal) do |f|
  = f.error_notification

  .form-inputs
    .large-2.columns= f.input :up
    .large-2.columns= f.input :down
    .large-2.columns= f.input :tried
    .large-6.columns
  %hr

  .form-actions
    = f.button :submit

= link_to 'Show', @goal
\|
= link_to 'Back', goals_path

app/views/goals/index.html.haml
%table#goals-table.display.compact.nowrap{"cellspacing" => 0, "width" => "100%"}
  %thead
    %tr
      %th
      %th.text-center #
      %th Labels
      %th Goal Title
      %th.text-center Author
      %th.text-center Created
      %th.text-center Tried
      %th.text-center= image_tag(asset_path('up.jpeg'), width: 40, height: 40)
      %th.text-center= image_tag(asset_path('down.jpeg'), width: 40, height: 40)
      %th.text-center= image_tag(asset_path('check.png'), width: 40, height: 40)

  %tbody
    - @goals.each do |goal|
      %tr
        %td= link_to goal.description
        %td.text-center= link_to goal.id, goal.issue_path, title: 'See GitHub Issue/Goal'
        %td= render 'labels', goal: goal
        %td
          = button_to "Review", new_review_path(goal_id: goal.id)
          = link_to "#{goal.title}...", goal
          = link_to goal.issue_path do
            = image_tag(asset_path('octocat.png'), width: 30, height: 30)
        %td.text-center= link_to goal.created_by, User.github_path(goal.created_by)
        %td.text-center= goal.created.strftime('%m/%d')
        %td.text-center= link_to goal.tried, edit_goal_path(goal), title: "Tried by #{pluralize(goal.tried, 'group')}"
        %td.text-center= link_to goal.up, edit_goal_path(goal), title: "Upvoted #{pluralize(goal.up || 0, 'time')}"
        %td.text-center= link_to goal.down, edit_goal_path(goal), title: "Downvoted #{pluralize(goal.down || 0, 'time')}"
        %td.text-center= link_to goal.reviews.count || 0, goal, title: "Reviewed by #{pluralize(goal.reviews.count || 0, 'player')}"
        / %td= link_to 'Destroy', goal, :method => :delete, :data => { :confirm => 'Are you sure?' }

%hr

%p
  Syncs hourly with GitHub issues.  Last sync
  - if Goal.last_update
    = Goal.last_update.in_time_zone('Pacific Time (US & Canada)').strftime('%b-%d %H:%M %Z')

app/views/goals/new.html.haml
%h1 Add Goal

= simple_form_for(@goal) do |f|
  = f.error_notification

  .form-inputs
    = f.input :id, collection: @importable_ids, label: 'web-development-js issue id'

  .form-actions
    = f.button :submit

= link_to 'Back', goals_path

app/views/goals/show.html.haml
%h3= "Goal ##{@goal.id}: #{@goal.title}"

Created By
%b= link_to @goal.created_by, User.github_path(@goal.created_by)

%hr
%h4 Labels
= render 'labels', goal: @goal
%hr

%h4
  = "#{@goal.reviews.count} Reviews"
  \—
  = link_to "Add Yours", new_review_path(goal_id: @goal.id)
= render @goal.reviews

%hr

%h4= link_to @goal.issue_path, @goal.issue_path
= markdown @goal.description

%hr

= link_to 'Edit', edit_goal_path(@goal)
\|
= link_to 'Back', goals_path