config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :goals
  resources :users
  root to: 'goals#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  get '/about' => 'visitors#about'

  namespace :api do
    namespace :v1 do
      resources :goals, only: [:index, :show]
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:player_id, :goal_id, :interest, :clarity, :difficulty_anticipated, :difficulty_hindsight, :relevance, :comments_before, :comments_after)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= simple_form_for(@review) do |f|
  = f.error_notification

  .form-inputs
    .large-4.columns= f.association :player, autofocus: true
    .large-8.columns= f.association :goal, collection: Goal.order(:id), label_method: :id_title
    .large-4.columns= f.input :interest, collection: INTEREST_OPTIONS, label: 'How interested I am'
    .large-4.columns= f.input :clarity, collection: CLARITY_OPTIONS, label: 'Clarity of Specs'
    .large-4.columns= f.input :relevance, collection: RELEVANCE_OPTIONS, label: 'Relevant to full-stack js goal'
    .large-6.columns= f.input :difficulty_anticipated, collection: DIFFICULTY_OPTIONS
    .large-6.columns= f.input :difficulty_hindsight, collection: DIFFICULTY_OPTIONS
    .large-6.columns= f.input :comments_before, input_html: {rows: 4}
    .large-6.columns= f.input :comments_after, input_html: {rows: 4}

  .form-actions
    = f.button :submit

app/views/reviews/_review.html.haml
= link_to "#{review.player.name} — Interest #{review.interest} — #{review.created_at.strftime('%b-%d')}", review
%br

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Listing Reviews

%table
  %thead
    %tr
      %th Player
      %th Goal
      %th Interest
      %th Clarity
      %th Diff. anticipated
      %th Diff. hindsight
      %th Relevance
      %th
      %th
      %th

  %tbody
    - @reviews.each do |review|
      %tr
        %td= link_to review.player.name, review.player
        %td= link_to review.goal.title, review.goal
        %td= review.interest
        %td= review.clarity
        %td= review.difficulty_anticipated
        %td= review.difficulty_hindsight
        %td= review.relevance
        %td= link_to 'Show', review
        %td= link_to 'Edit', edit_review_path(review)
        %td= link_to 'Destroy', review, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.haml
%h1 New Review

= render 'form'

= link_to 'Back', reviews_path

app/views/reviews/show.html.haml
%p#notice= notice

%p
  %b Player:
  = @review.player_id
%p
  %b Goal:
  = @review.goal_id
%p
  %b Interest:
  = @review.interest
%p
  %b Clarity:
  = @review.clarity
%p
  %b Difficulty anticipated:
  = @review.difficulty_anticipated
%p
  %b Difficulty hindsight:
  = @review.difficulty_hindsight
%p
  %b Relevance:
  = @review.relevance
%p
  %b Comments before:
  = @review.comments_before
%p
  %b Comments after:
  = @review.comments_after

= link_to 'Edit', edit_review_path(@review)
\|
= link_to 'Back', reviews_path