config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :goals
  resources :users
  root to: 'goals#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  get '/about' => 'visitors#about'

  namespace :api do
    namespace :v1 do
      resources :goals, only: [:index, :show]
    end
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Sign out', signout_path
- else
  %li= link_to 'Sign in', signin_path

- if user_signed_in?
  - if current_user.try(:admin?)
    %li= link_to 'Users', users_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Goals (Re)Viewer Home', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        Menu
  .top-bar-section
    %ul
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Goals', goals_path
%li= link_to 'Add Goal/Issue', 'https://github.com/GuildCrafts/web-development-js/issues/new', target: :external
%li= link_to 'Add Review', new_review_path
%li= link_to 'Browse Reviews', reviews_path
%li= link_to 'About', about_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Goals (Re)Viewer'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Goals Viewer'}"}
    = stylesheet_link_tag 'application', media: 'all'
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield